coffee_shop/ankieta/urls.py
import django


from django.urls import path

from ankieta.models import Odpowiedz
from . import views
app_name="ankieta"
urlpatterns=[
    path('',views.index,name='index'),
    path('pytania/',views.pytania,name='pytania'),
    path('pytania/<int:pytanie_id>/',views.szczegoly,name='szczegoly'),
    path('pytania/<int:pytanie_id>/glosuj/',views.glosuj,name='glosuj'),
    path('pytania/<int:pytanie_id>/wyniki/',views.pokaz_rezultat_glosowania,name='wyniki'),
    
]

coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('ankieta/',include('ankieta.urls')),
    path('admin/', admin.site.urls),
]

coffee_shop/ankieta/models.py
from datetime import datetime
from pyexpat import model
from tabnanny import verbose
from django.db import models

# Create your models here.
class Pytanie(models.Model):
    tekst_pytania = models.CharField(max_length=400)
    data_publikacji = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.tekst_pytania.upper()} - {self.data_publikacji.strftime("%m/%d/%Y, %H:%M:%S")}' 

    class Meta:
        verbose_name="Pytanie"
        verbose_name_plural="Pytania"
        ordering= ("data_publikacji",)

class Odpowiedz(models.Model):
    pytanie=models.ForeignKey(Pytanie,on_delete=models.CASCADE)
    tekst_wyboru=models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.pytanie} - {self.tekst_wyboru}'

    class Meta:
        verbose_name="Odpowiedź"
        verbose_name_plural="Odpowiedzi"
        
class Glosy(models.Model):
    odpowiedz=models.ForeignKey(Odpowiedz,on_delete=models.CASCADE)
    pytanie=models.ForeignKey(Pytanie,on_delete=models.CASCADE)
    uzytkownik=models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.uzytkownik} - {self.pytanie.id} - {self.odpowiedz.id}'
    
    class Meta:
        verbose_name="Głos"
        verbose_name_plural="Głosy"

    

coffee_shop/ankieta/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from .models import Pytanie,Glosy
from django.template import loader
from django.db.models import Count

# Create your views here.
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[0]
    return request.META.get('REMOTE_ADDR')


def index(request):
    return HttpResponse("To jest strona mojej aplikacji!!!")


def pytania(request):
    # return HttpResponse("To są wszystkie pytania")
    lista_ostatnich_pytan=Pytanie.objects.all()[:5]
    return render(request,'ankieta\pytania.html',{'lista_ostatnich_pytan':lista_ostatnich_pytan})


def szczegoly(request, pytanie_id):
    pytanie=get_object_or_404(Pytanie, pk=pytanie_id)
    return render(request, 'ankieta/szczegoly.html',{'pytanie':pytanie})


def wyniki(request,pytanie_id):
    return HttpResponse(f"To są wyniki pytania {pytanie_id}")

def glosuj(request, pytanie_id):
    Glosy.objects.create(pytanie_id=pytanie_id,odpowiedz_id=request.POST['wybor'],
    uzytkownik= get_client_ip(request))          
    return HttpResponseRedirect(f"/ankieta/pytania/{pytanie_id}/wyniki")

# def pokaz_rezultat_glosowania(request,pytanie_id):
#     # get_object_or_404(Pytanie,pytanie_id)
#     glosy = Glosy.objects.filter(pytanie_id=pytanie_id)
#     odpowiedzi={}
#     for glos in glosy:
#         if current_value:=odpowiedzi.get(glos.odpowiedz.tekst_wyboru):
#             odpowiedzi[glos.odpowiedz.tekst_wyboru]=current_value+1
#         else:
#            odpowiedzi[glos.odpowiedz.tekst_wyboru]=1
#     return JsonResponse(odpowiedzi)

def pokaz_rezultat_glosowania(request,pytanie_id):
    results=Glosy.objects.filter(pytanie_id=pytanie_id).values(
        'odpowiedz__tekst_wyboru').annotate(Count('odpowiedz_id'))
    return JsonResponse(list(results),safe=False)

coffee_shop/ankieta/templates/ankieta/pytania.html
    {% extends "base.html" %}
    {% block title%}Lista ankiet{% endblock %}

    {% block content %}
    {% if lista_ostatnich_pytan %}
    <ul>
        {% for pytanie in lista_ostatnich_pytan %}
        <li><a href="/ankieta/pytania/{{pytanie.id}}/">
                {{pytanie.tekst_pytania}}
            </a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nie ma jeszcze ankiet </p>
    {% endif %}
    {% endblock %}

coffee_shop/ankieta/templates/ankieta/szczegoly.html
{% extends "base.html" %}
{% block title%}Ankieta - szczegóły{% endblock %}

{% block content %}
<form action="{% url 'ankieta:glosuj' pytanie.id %}" method="post">
    {% csrf_token %}
    <a href="/ankieta/pytania/" class="btn btn-warning" tabindex="-1" role="button"
        aria-disabled="true">{{pytanie.tekst_pytania}}</a>

    <ul>
        {% for odp in pytanie.odpowiedz_set.all %}

        <input type="radio" name="wybor" id="wybor{{ forloop.counter }}" value="{{odp.id}}">
        <label for="wybor{{ forloop.counter }}">{{odp.tekst_wyboru}}</label><br>

        {% endfor %}
    </ul>
    <input type="submit" value="Głosuj">
</form>
{% endblock %}

coffee_shop/ankieta/templates/base.html
<!doctype html>
<html lang="pl">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <div class="container mt-5">
        {%block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>


</body>

</html>