medyczny/medyczny/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('recepta/', include('recepta.urls')),
    path('admin/', admin.site.urls),
]

medyczny/recepta/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index, name='index'),
]

medyczny/recepta/models.py
from datetime import datetime
from random import randint
from statistics import mode
from tkinter import CASCADE
from django.db import models

def random_string():

    return str(randint(1000, 9999))

class adres(models.Model):
    miasto = models.CharField(max_length=50)
    kod_pocztowy = models.CharField(max_length=6)
    ulica = models.CharField(max_length=250)
    nr_domu = models.CharField(max_length=5)
    nr_mieszkania = models.CharField(max_length=4)

    def __str__(self):
        return f'{self.miasto}, {self.ulica} {self.nr_domu}' 

    class Meta:
        verbose_name="Adres"
        verbose_name_plural="Adresy"
        ordering= ("miasto",)
    
    
    
class osoba(models.Model):
    imie = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=50)
    pesel= models.CharField(max_length=11)
    is_staff=models.BooleanField(default=False)
    specjalizacja=models.CharField(max_length=100)
    adres=models.ForeignKey(adres, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nazwisko}, {self.imie}' 

    class Meta:
        verbose_name="Osoba"
        verbose_name_plural="Osoby"
        ordering= ("nazwisko",)


class recepta(models.Model):
    kod_recepty=random_string()
    pacjent=models.ForeignKey(osoba, related_name='pacjent', on_delete=models.CASCADE)
    wystawca=models.ForeignKey(osoba, on_delete=models.CASCADE)
    data_wystawienia= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.kod_recepty}' 

    class Meta:
        verbose_name="Recepta"
        verbose_name_plural="Recepty"
        ordering= ("-data_wystawienia",)
            
    # payment_fraction = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
class przepisane_leki(models.Model):
    recepta=models.ForeignKey(recepta, on_delete=models.CASCADE)
    nazwa_leku=models.CharField(max_length=250)
    dawkowanie=models.CharField(max_length=2000)
    odplatnosc=models.IntegerField()
    
    def __str__(self):
        return f'{self.nazwa_leku.upper()}' 

    class Meta:
        verbose_name="Lek"
        verbose_name_plural="Leki"
        ordering= ("nazwa_leku",)
    
    

medyczny/recepta/views.py
from multiprocessing import context
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import osoba,adres,recepta,przepisane_leki

# Create your views here.

def index(request):
    dane=recepta.objects.order_by("-data_wystawienia")
    
    context={'tytul': 'Moja aplikacja medyczna',
             'lista_recept': dane} 
    return render(request,'recepta/index.html',context)

medyczny/recepta/templates/base.html
<!doctype html>
<html lang="pl">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>APLKACJA MEDYCZNA - {% block title %}{% endblock %}</title>
</head>

<body>
    <div class="container shadow-lg p-3 mb-5 mt-5 bg-body rounded">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

medyczny/recepta/templates/recepta/index.html
 {% extends 'base.html' %}
 {% block title %} strona główna {% endblock%}

 {% block content %}
 <h1>{{tytul}}</h1>

 {% for recepta in lista_recept %}
 <h4>{{recepta.pacjent}}</h4>

 <div class="accordion accordion-flush" id="accordionFlushExample">
     <div class="accordion-item">
         <h2 class="accordion-header" id="flush-headingOne">
             <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                 data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false"
                 aria-controls="collapse{{ forloop.counter }}">
                 Pacjent: {{recepta.pacjent}},wystawił: {{recepta.wystawca}} data: {{recepta.data_wystawienia}}
             </button>
         </h2>
         <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
             aria-labelledby="collapse{{ forloop.counter }}" data-bs-parent="#accordionFlushExample">
             <div class="accordion-body">
                 <table class="table">
                     <thead>
                         <tr>
                             <th scope="col">#</th>
                             <th scope="col">Nazwa leku</th>
                             <th scope="col">Dawkowanie</th>
                             <th scope="col">Odpłatność</th>
                         </tr>
                     </thead>
                     <tbody>
                         {% for szcz in recepta.przepisane_leki_set.all %}
                         <tr>
                             <th scope="row">{{forloop.counter}}</th>
                             <td>{{szcz.nazwa_leku}}</td>
                             <td>{{szcz.dawkowanie}}</td>
                             <td>{{szcz.odplatnosc}}</td>
                         </tr>
                         {% endfor %}
                     </tbody>
                 </table>
             </div>
         </div>

     </div>







     {% endfor %}

     {% endblock %}